[workspace]
resolver = "3"
members = [
    "casino-core",
    "game-roulette",
    "robot-sdk",
    "wasm-robot",
    "engine",
    "ui-cli",
    "robot-wasm-loader",
    "wasm-robot",
    "wasm-robot-blackonly",
]
