[package]
name = "robot-wasm-loader"
version = "0.1.0"
edition = "2024"

[dependencies]
casino-core = {path = "../casino-core"}
extism = "1.11.1"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
robot-sdk = { path = "../robot-sdk" }