[package]
name = "ui-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
casino-core = {path = "../casino-core"}
robot-sdk = { path = "../robot-sdk" }
robot-wasm-loader = { path = "../robot-wasm-loader"}
engine = {path = "../engine"}
